#!/usr/bin/env python3
"""Generate BuiltinPatchNames.h from AMY's src/patches.h.

AMY bakes its 258 built-in patches into `patch_commands[]` as `/* N: Name */ "wire
commands"` entries (the same source AMY's web build parses in gen_patches_js.py).
The name comments are stripped from the compiled library and the command array is
file-local `static`, so we extract BOTH at build time into a C++ header:
  * kBuiltinPatchNames[]    — for the patch browser.
  * kBuiltinPatchCommands[] — the raw wire string per patch, so "Load into Editor"
                              can decode a factory patch's parameters (no runtime
                              AMY read-back API exists).

Usage: gen_patch_names.py <path/to/patches.h> <path/to/output/BuiltinPatchNames.h>
"""
import re
import sys

# /* N: Name */ "wire commands"   (the command literal has no embedded quotes)
ENTRY = re.compile(r'/\*\s*(\d+):\s*(.*?)\s*\*/\s*"([^"]*)"')


def parse_patches(source: str) -> list[tuple[str, str]]:
    by_index = {}
    for m in ENTRY.finditer(source):
        by_index[int(m.group(1))] = (m.group(2), m.group(3))
    if not by_index:
        raise SystemExit("gen_patch_names: no '/* N: Name */ \"...\"' entries found in patches.h")
    count = max(by_index) + 1
    return [by_index.get(i, (f"Patch {i}", "")) for i in range(count)]


def c_escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_patch_names.py <patches.h> <output.h>")
    src = open(sys.argv[1], 'r', encoding='utf-8', errors='replace').read()
    patches = parse_patches(src)

    lines = [
        "// AUTO-GENERATED by scripts/gen_patch_names.py — do not edit by hand.",
        "// Source: third_party/amy/src/patches.h",
        "#pragma once",
        "",
        "namespace amyplug",
        "{",
        f"inline constexpr int kBuiltinPatchCount = {len(patches)};",
        "inline constexpr const char* const kBuiltinPatchNames[kBuiltinPatchCount] = {",
    ]
    lines += [f'    "{c_escape(n)}",' for n, _ in patches]
    lines += [
        "};",
        "",
        "// The full wire-command string for each built-in patch (empty if unparsed).",
        "inline constexpr const char* const kBuiltinPatchCommands[kBuiltinPatchCount] = {",
    ]
    lines += [f'    "{c_escape(c)}",' for _, c in patches]
    lines += ["};", "} // namespace amyplug", ""]

    with open(sys.argv[2], 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
