#!/usr/bin/env python3
"""Generate BuiltinPatchNames.h from AMY's src/patches.h.

AMY bakes its 258 built-in patches into `patch_commands[]` with a human-readable
name in a `/* N: Name */` comment before each entry (the same source AMY's web
build parses in scripts/gen_patches_js.py). Those comments are stripped from the
compiled library, so we extract them at build time into a C++ header AMYplug's
patch browser can display.

Usage: gen_patch_names.py <path/to/patches.h> <path/to/output/BuiltinPatchNames.h>
"""
import re
import sys

ENTRY = re.compile(r'/\*\s*(\d+):\s*(.*?)\s*\*/')


def parse_names(source: str) -> list[str]:
    by_index = {}
    for m in ENTRY.finditer(source):
        by_index[int(m.group(1))] = m.group(2)
    if not by_index:
        raise SystemExit("gen_patch_names: no '/* N: Name */' entries found in patches.h")
    count = max(by_index) + 1
    return [by_index.get(i, f"Patch {i}") for i in range(count)]


def c_escape(s: str) -> str:
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_patch_names.py <patches.h> <output.h>")
    src = open(sys.argv[1], 'r', encoding='utf-8', errors='replace').read()
    names = parse_names(src)

    lines = [
        "// AUTO-GENERATED by scripts/gen_patch_names.py — do not edit by hand.",
        "// Source: third_party/amy/src/patches.h",
        "#pragma once",
        "",
        "namespace amyplug",
        "{",
        f"inline constexpr int kBuiltinPatchCount = {len(names)};",
        "inline constexpr const char* const kBuiltinPatchNames[kBuiltinPatchCount] = {",
    ]
    lines += [f'    "{c_escape(n)}",' for n in names]
    lines += ["};", "} // namespace amyplug", ""]

    with open(sys.argv[2], 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
